services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  postgres:
    image: postgres:15-alpine
    container_name: devsecops_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=supersecret_bootstrap_password
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"

  vault:
    image: hashicorp/vault:latest
    container_name: devsecops_vault
    environment:
      # In a real environment, NEVER use a dev root token. 
      # We use this strictly for local lab bootstrapping.
      - VAULT_DEV_ROOT_TOKEN_ID=dev-root-token
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
volumes:
  localstack_data: